In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("car_evaluation.csv")  # Sesuaikan dengan nama file kamu
print(df.head())



   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc


In [3]:
le = LabelEncoder()
for col in df.columns:
    df[col] = le.fit_transform(df[col])


In [4]:
X = df.drop('class', axis=1)  # Asumsikan kolom target bernama 'class'
y = df['class']


KeyError: "['class'] not found in axis"

In [5]:
print(df.columns)

Index(['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')


In [6]:
X = df.drop('class', axis=1)
y = df['class']

KeyError: "['class'] not found in axis"

In [7]:
X = df.drop('acceptability', axis=1)
y = df['acceptability']

KeyError: "['acceptability'] not found in axis"

In [8]:
column_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [9]:
df = pd.read_csv("car_evaluation.csv", header=None, names=column_names)


In [10]:
X = df.drop('class', axis=1)
y = df['class']

In [11]:
from sklearn.preprocessing import LabelEncoder


In [12]:
le = LabelEncoder()
X = X.apply(le.fit_transform)  # Encode semua kolom fitur
y = le.fit_transform(y)        # Encode target (class)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [15]:
from sklearn.tree import DecisionTreeClassifier


In [16]:
model = DecisionTreeClassifier(criterion='entropy', random_state=42)
model.fit(X_train, y_train)


DecisionTreeClassifier(criterion='entropy', random_state=42)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [18]:
y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:", accuracy_score(y_test, y_pred))


Confusion Matrix:
[[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   0   0  16]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.92      0.94        83
           1       0.62      0.91      0.74        11
           2       1.00      1.00      1.00       235
           3       1.00      0.94      0.97        17

    accuracy                           0.97       346
   macro avg       0.90      0.94      0.91       346
weighted avg       0.98      0.97      0.98       346


Accuracy Score: 0.9739884393063584
